version: '2'

services:
  products_api:
    image: registry.gitlab.com/taxpayercorner-vs/microservices/store-info-service:production
    ports:
     - "8005:8005"
    restart: always
    environment:
     - NODE_ENV=production
